//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::B14, // B14 Output
	Gpio::D12, // Low Side (D12)
// "B14 Output",
// "Low Side (D12)",
}
