//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::B14, // B14 Output
	Gpio::D7, // Low Side 1
	Gpio::D9, // Low Side 2
	Gpio::D10, // Low Side 3
// "B14 Output",
// "Low Side 1",
// "Low Side 2",
// "Low Side 3",
}
